INSERT INTO review (id, date_created, rating, description, plate) VALUES
(1, '2025-01-15T10:00:00', 4.5, 'The dish was delicious! The flavors complemented each other really well, and the presentation was beautiful. The seasoning was spot on, and the texture of the ingredients was perfect. A little more heat would have made it even better, but overall, it was a fantastic meal. Highly recommend!', 1),
(2, '2025-01-15T10:15:00', 5.0, 'This dish exceeded my expectations! The flavors were bold and well-balanced, and the ingredients were fresh and perfectly cooked. The textures were fantastic, and the seasoning was just right. I will definitely be coming back for this one. Truly a top-tier dish!', 2),
(3, '2025-01-15T10:30:00', 3.5, 'The dish was good but not great. It was a little bland for my taste, and I was expecting more spice. The texture was fine, and the presentation was nice, but overall, it didn’t leave a lasting impression. Still a solid choice, just not remarkable.', 3),
(4, '2025-01-15T10:45:00', 4.0, 'I enjoyed this dish. The ingredients were fresh, and the flavors were well-balanced. The meat was cooked nicely, though I wish there had been a bit more seasoning. Overall, a solid meal, but it could use a little more depth to really stand out.', 4),
(5, '2025-01-15T11:00:00', 4.8, 'Absolutely delicious! The spices were perfectly balanced, and everything was cooked to perfection. The flavors were vibrant and fresh, and the dish had just the right amount of heat. I can’t wait to order this again. One of the best meals I’ve had recently!', 5),
(6, '2025-01-15T11:15:00', 2.0, 'Unfortunately, this dish didn’t work for me. It was too salty, and I couldn’t really enjoy the other flavors. The meat was a bit tough, and the presentation wasn’t as appealing as I had hoped. It just didn’t come together well. Disappointing overall.', 6),
(7, '2025-01-15T11:30:00', 5.0, 'This was fantastic! Every bite was full of flavor, and the dish was perfectly balanced. The ingredients were fresh, and the textures were great. It’s rare to find a meal this satisfying. Definitely a must-try and one I will order again!', 7),
(8, '2025-01-15T11:45:00', 3.0, 'The dish was okay, but it didn’t blow me away. The flavors were decent, but a bit on the bland side. I think it could have used more seasoning or a different sauce. The presentation was fine, but it was missing that wow factor. Wouldn’t rush to order it again.', 8),
(9, '2025-01-15T12:00:00', 4.2, 'A solid meal overall. The flavors were well-balanced, and the portion size was generous. I loved the freshness of the ingredients. The only downside was that the dish could’ve used a little more spice or seasoning to elevate the flavor. Still, I would order it again.', 9),
(10, '2025-01-15T12:15:00', 4.7, 'This was a really great dish. The flavors were fresh and vibrant, and the meat was tender. The seasoning was almost perfect, though I would have liked a bit more kick in the sauce. Overall, a very satisfying and well-executed dish. Highly recommend!', 10),
(11, '2025-01-15T12:30:00', 3.8, 'The dish was decent, but I felt it could have been more flavorful. The textures were good, but the seasoning was a bit too mild. The presentation was fine, but overall, it didn’t leave a lasting impression. A decent meal, but not my favorite.', 11),
(12, '2025-01-15T12:45:00', 4.9, 'Absolutely perfect! This dish was flavorful, beautifully presented, and perfectly cooked. The seasoning was bold yet balanced, and the textures were fantastic. I loved every bite. Without a doubt, one of the best meals I’ve had in a while. I’ll definitely be back!', 12),
(13, '2025-01-15T13:00:00', 2.5, 'I was disappointed with this dish. The meat was undercooked, and the flavors were not well balanced. The sauce was too bland, and it just didn’t work for me. I ended up not finishing it. I might give it another shot, but this was not a good experience.', 13),
(14, '2025-01-15T13:15:00', 4.3, 'A very tasty dish. The flavors were good, and the portion size was satisfying. The meat was tender, and the vegetables were fresh. However, I felt the seasoning could have been more pronounced. Still, a solid and enjoyable meal overall.', 14),
(15, '2025-01-15T13:30:00', 3.9, 'It was a good dish, but not amazing. The flavors were fine, though they didn’t quite pop. The meat was cooked well, but the sauce felt a little too light. A decent meal, but I was hoping for a little more complexity and spice.', 15),
(16, '2025-01-15T13:45:00', 5.0, 'This was an exceptional meal! The dish was beautifully cooked, and the flavors were perfectly balanced. The textures of the vegetables and meat complemented each other perfectly. I can’t wait to try it again. A true 5-star experience!', 16),
(17, '2025-01-15T14:00:00', 4.0, 'Good, but not quite as exciting as I had hoped. The flavors were nice, and the dish was satisfying, but it didn’t have that wow factor. The seasoning could have been more bold. Still, a very solid meal, and I’d happily order it again.', 17),
(18, '2025-01-15T14:15:00', 4.4, 'A very tasty dish. The flavors were well-balanced, and the meat was perfectly cooked. The vegetables were fresh, though I would have liked a little more seasoning. Overall, I really enjoyed it, and I’d definitely order it again next time.', 18),
(19, '2025-01-15T14:30:00', 3.7, 'This dish was okay, but it didn’t quite hit the mark for me. The seasoning was a bit too mild, and it lacked depth. The vegetables were cooked well, but the sauce didn’t do much for me. It was fine, but I was expecting more flavor.', 19),
(20, '2025-01-15T14:45:00', 4.1, 'Nice dish overall. The flavors were good, and the meat was tender. The vegetables were fresh, and the portion size was generous. I did feel the seasoning could have been a little bolder, but overall, it was a solid and satisfying meal.', 20),
(21, '2025-01-15T15:00:00', 5.0, 'This dish was amazing! The flavors were bold, the meat was tender, and the presentation was beautiful. Everything came together perfectly. I loved the combination of spices and the textures were spot on. One of the best meals I’ve had in a long time!', 1),
(22, '2025-01-15T15:15:00', 4.6, 'Very good! The dish had great flavors, and the portion was just right. The meat was tender, and the vegetables were fresh. I did feel it could have used a bit more seasoning or spice, but overall, it was a very satisfying and delicious meal.', 2),
(23, '2025-01-15T15:30:00', 3.4, 'The dish was decent, but a little underwhelming. The flavors were fine, but I felt it lacked some complexity. The meat was cooked well, but the sauce didn’t quite hit the mark for me. It was an okay meal, but I expected a little more excitement.', 3);



